# -*- coding: utf-8 -*-
"""BoxParticle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BumwLpeSOOwAWe_6McD8_d8IDRMbJXVu
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

fig, ax = plt.subplots()
ax.set_ylim(0, 1)
p=np.random.rand(20)
points, = ax.plot(p, 'o')
def recorrido(x):
  ax.set_ydata(0,1)
  return points,

def puntos(x,dt=0.01,vx=2,vy=0.3):
  np.copy(p)



ani=FuncAnimation(fig,puntos,frames=100,init_func=recorrido,blit=True)
from IPython.display import HTML
HTML(ani.to_jshtml())

#####################################################################################

fig, ax = plt.subplots()
ax.set_ylim(0, 1)
p=np.random.rand(500)
points = ax.plot(p, 'o')